name: Build GenSafe APK

on:
  workflow_dispatch: 

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code from GitHub
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create folder and copy files
        run: |
          mkdir www
          # یہ آپ کے NewGenSafe فولڈر کی تمام فائلوں اور ذیلی فولڈرز کو کاپی کرے گا
          rsync -a NewGenSafe/ www/
          # یہ ایپ کے اندر آپ کی مین فائل کو index.html بنا دے گا تاکہ ایپ درست کھلے
          mv www/GenSafe.html www/index.html

      - name: Install Capacitor & Create App
        run: |
          npm init -y
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx cap init GenSafe com.offline.gensafe --web-dir www
          npx cap add android
          npx cap sync android

      - name: Build the APK File
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK for Download
        uses: actions/upload-artifact@v4
        with:
          name: GenSafe-Offline-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
